import os

# large files: "FOX",        "RTB",
CZ_LOBS = {"SIS": 1,
           "DWA": 1,
           "MWB": 1,
           "DAR": 1,
           "SMS": 1,
           "PCF": 1,
           "PPC": 1,
           "TCF": 1,
           "GSM": 1,
           "TPP": 1,
           "XTC": 1,
           "PST": 1,
           "WHS": 1,
           "TAP": 1,
           "SBC": 1,
           "SCF": 1,
           "LAS": 1,
           "MMS": 1,
           "ATS": 1,
           "RRA": 1,
           "VMS": 1,
           "MTS": 1,
           "OTA": 1,
           "BVS": 1,
           "VOP": 1,
           "WEL": 1,
           "CIR": 1,
           "SMG": 1,
           "LTP": 1,
           "M2M": 1,
           "EWG": 1,
           "TIT": 1,
           "RES": 1,
           "KPI": 1,
           "EPC": 1,
           "MNT": 1,
           "TOC": 1,
           "EWH": 1,
           "ACI": 1}
LOBS = {"CZ": CZ_LOBS}


class Lob:
  def __init__(self, country, name, granularity=None, smooth=True):
    self.country = country;
    self.name = name
    self.granularity = granularity
    self.smooth = smooth

#
# LOBS = [
#   Lob("CZ", "SIS", 180),
#   Lob("CZ", "DWA", 10),
#   Lob("CZ", "MWB", 10),
#   Lob("CZ", "DAR", 15),
#   Lob("CZ", "SMS", 10),
#   Lob("CZ", "PCF", 15),
#   Lob("CZ", "PPC", 15),
#   Lob("CZ", "TCF", 30),
#   Lob("CZ", "GSM", 15),
#   Lob("CZ", "TPP", 60),
#   Lob("CZ", "XTC", 15),
#   Lob("CZ", "PST", 60),
#   Lob("CZ", "WHS", 10),
#   Lob("CZ", "TAP", 120),
#   Lob("CZ", "SBC", 90),
#   Lob("CZ", "SCF", 180),
#   Lob("CZ", "LAS", 15),
#   Lob("CZ", "MMS", 15),
#   Lob("CZ", "ATS", 15),
#   Lob("CZ", "RRA", 60),
#   Lob("CZ", "VMS", 60),
#   Lob("CZ", "MTS", 15),
#   Lob("CZ", "OTA", 30),
#   Lob("CZ", "BVS", 15),
#   Lob("CZ", "VOP", 20),
#   Lob("CZ", "WEL", 60),
#   Lob("CZ", "CIR", 60),
#   Lob("CZ", "SMG", 60),
#   Lob("CZ", "LTP", 1440),
#   Lob("CZ", "M2M", 1440),
#   Lob("CZ", "EWG", 180),
#   Lob("CZ", "TIT", 120),
#   Lob("CZ", "RES", 1440),
#   Lob("CZ", "KPI", 1440),
#   Lob("CZ", "EPC", 120),
#   Lob("CZ", "MNT", 10),
#   Lob("CZ", "TOC", 1440),
#   Lob("CZ", "EWH", 60),
#   Lob("CZ", "ACI", 10),
#   Lob("CZ", "ICG", 60)
# ]
